/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyaccountRouteImport } from './routes/myaccount'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyaccountTransactionHistoryRouteImport } from './routes/myaccount/transaction-history'
import { Route as MyaccountProfileRouteImport } from './routes/myaccount/profile'
import { Route as MyaccountManageSubscriptionRouteImport } from './routes/myaccount/manage-subscription'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyaccountRoute = MyaccountRouteImport.update({
  id: '/myaccount',
  path: '/myaccount',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyaccountTransactionHistoryRoute =
  MyaccountTransactionHistoryRouteImport.update({
    id: '/transaction-history',
    path: '/transaction-history',
    getParentRoute: () => MyaccountRoute,
  } as any)
const MyaccountProfileRoute = MyaccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MyaccountRoute,
} as any)
const MyaccountManageSubscriptionRoute =
  MyaccountManageSubscriptionRouteImport.update({
    id: '/manage-subscription',
    path: '/manage-subscription',
    getParentRoute: () => MyaccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/myaccount': typeof MyaccountRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/myaccount/manage-subscription': typeof MyaccountManageSubscriptionRoute
  '/myaccount/profile': typeof MyaccountProfileRoute
  '/myaccount/transaction-history': typeof MyaccountTransactionHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/myaccount': typeof MyaccountRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/myaccount/manage-subscription': typeof MyaccountManageSubscriptionRoute
  '/myaccount/profile': typeof MyaccountProfileRoute
  '/myaccount/transaction-history': typeof MyaccountTransactionHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/myaccount': typeof MyaccountRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/myaccount/manage-subscription': typeof MyaccountManageSubscriptionRoute
  '/myaccount/profile': typeof MyaccountProfileRoute
  '/myaccount/transaction-history': typeof MyaccountTransactionHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/myaccount'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/myaccount/manage-subscription'
    | '/myaccount/profile'
    | '/myaccount/transaction-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/myaccount'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/myaccount/manage-subscription'
    | '/myaccount/profile'
    | '/myaccount/transaction-history'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/myaccount'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/myaccount/manage-subscription'
    | '/myaccount/profile'
    | '/myaccount/transaction-history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MyaccountRoute: typeof MyaccountRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myaccount': {
      id: '/myaccount'
      path: '/myaccount'
      fullPath: '/myaccount'
      preLoaderRoute: typeof MyaccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myaccount/transaction-history': {
      id: '/myaccount/transaction-history'
      path: '/transaction-history'
      fullPath: '/myaccount/transaction-history'
      preLoaderRoute: typeof MyaccountTransactionHistoryRouteImport
      parentRoute: typeof MyaccountRoute
    }
    '/myaccount/profile': {
      id: '/myaccount/profile'
      path: '/profile'
      fullPath: '/myaccount/profile'
      preLoaderRoute: typeof MyaccountProfileRouteImport
      parentRoute: typeof MyaccountRoute
    }
    '/myaccount/manage-subscription': {
      id: '/myaccount/manage-subscription'
      path: '/manage-subscription'
      fullPath: '/myaccount/manage-subscription'
      preLoaderRoute: typeof MyaccountManageSubscriptionRouteImport
      parentRoute: typeof MyaccountRoute
    }
  }
}

interface MyaccountRouteChildren {
  MyaccountManageSubscriptionRoute: typeof MyaccountManageSubscriptionRoute
  MyaccountProfileRoute: typeof MyaccountProfileRoute
  MyaccountTransactionHistoryRoute: typeof MyaccountTransactionHistoryRoute
}

const MyaccountRouteChildren: MyaccountRouteChildren = {
  MyaccountManageSubscriptionRoute: MyaccountManageSubscriptionRoute,
  MyaccountProfileRoute: MyaccountProfileRoute,
  MyaccountTransactionHistoryRoute: MyaccountTransactionHistoryRoute,
}

const MyaccountRouteWithChildren = MyaccountRoute._addFileChildren(
  MyaccountRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MyaccountRoute: MyaccountRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
