name: Deploy Frontend

on:
  push:
    branches:
      - staging
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          script_stop: true
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            bash "${{ secrets.PROJECT_PATH }}/deploy.sh" "${{ secrets.PROJECT_PATH }}" "${{ github.ref_name }}"
